#!/bin/sh

#echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> .env
echo DOCKER_REGISTRY=$DOCKER_REGISTRY >> .env
echo CI_PIPELINE_IID=$CI_PIPELINE_IID >> .env
echo APP_NAME=$APP_NAME >> .env
echo IMAGE=$DOCKER_REGISTRY/$APP_NAME/$CI_PIPELINE_IID >> .env
